# Generated by Django 5.1.5 on 2025-02-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='de_name',
            new_name='dep_name',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='doc_spe',
            new_name='doc_spec',
        ),
    ]
