# Generated by Django 5.1.5 on 2025-03-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_doctor_patient_appoinment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoinment',
            new_name='Appointment',
        ),
    ]
